import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { afterEach, expect, test, vi } from 'vitest';
const mocks=vi.hoisted(()=>({init:vi.fn()}));vi.mock('vgpu',()=>({init:mocks.init}));vi.mock('vgpu/scene',()=>({perspectiveCamera:()=>({viewProjection:new Float32Array(16)})}));
import { Controls } from './controls'; import { createRenderer } from './renderer'; import { DEFAULT_INSTANCED_RENDERING_CONTROLS } from './types';
function deferred(){let resolve!:()=>void;const promise=new Promise<void>(r=>resolve=r);return{promise,resolve};}
afterEach(()=>{vi.unstubAllGlobals();vi.clearAllMocks();});
test('shares 50 cubed default with accessible count select',()=>{const html=renderToStaticMarkup(createElement(Controls, { value: DEFAULT_INSTANCED_RENDERING_CONTROLS, onChange: () => {} }));expect(DEFAULT_INSTANCED_RENDERING_CONTROLS.count).toBe(50);expect(html).toContain('aria-label="Instance count (1M is an opt-in stress test)"');expect(html).toContain('value="50" selected');});
test('destroys a stale async rebuild and retains the newest completion',async()=>{vi.stubGlobal('window',{devicePixelRatio:1,addEventListener:vi.fn(),removeEventListener:vi.fn()});vi.stubGlobal('requestAnimationFrame',vi.fn(()=>1));vi.stubGlobal('cancelAnimationFrame',vi.fn());vi.stubGlobal('ResizeObserver',class{observe=vi.fn();disconnect=vi.fn();});const waits=[deferred(),deferred(),deferred()];const meshes=waits.map(()=>({destroy:vi.fn()}));let i=0;const gpu={time:0,surface:()=>({size:[100,50],format:'bgra8unorm',dispose:vi.fn()}),target:()=>({size:[100,50],format:'rgba8unorm',resize:vi.fn(),destroy:vi.fn()}),effect:()=>({set:vi.fn(),compile:vi.fn(async()=>{})}),sampler:()=>({}),mesh:()=>meshes[i],draw:()=>({set:vi.fn(),compile:()=>waits[i++].promise}),bundle:()=>({}),frame:{loop:vi.fn(()=>({stop:vi.fn()}))},dispose:vi.fn()};mocks.init.mockResolvedValueOnce(gpu);const r=createRenderer({canvas:{getBoundingClientRect:()=>({width:100,height:50})} as HTMLCanvasElement});await vi.waitFor(()=>expect(i).toBe(1));waits[0].resolve();await r.ready;r.setControls?.({count:100});await vi.waitFor(()=>expect(i).toBe(2));r.setControls?.({count:50}); // same as initial is accepted because requested state is 100
await vi.waitFor(()=>expect(i).toBe(3));waits[2].resolve();await Promise.resolve();waits[1].resolve();await vi.waitFor(()=>expect(meshes[1].destroy).toHaveBeenCalledOnce());expect(meshes[2].destroy).not.toHaveBeenCalled();r.dispose();expect(meshes[2].destroy).toHaveBeenCalledOnce();});
