import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { afterEach, expect, test, vi } from 'vitest';
const mocks=vi.hoisted(()=>({init:vi.fn()}));vi.mock('vgpu',()=>({init:mocks.init}));vi.mock('vgpu/scene',()=>({perspectiveCamera:()=>({viewProjection:new Float32Array(16)})}));
import { Controls } from './controls'; import { createRenderer, renderThumbnail } from './renderer'; import { DEFAULT_INSTANCED_RENDERING_CONTROLS } from './types';
function deferred(){let resolve!:()=>void;const promise=new Promise<void>(r=>resolve=r);return{promise,resolve};}
afterEach(()=>{vi.unstubAllGlobals();vi.clearAllMocks();});
test('shares 50 cubed default with accessible count select',()=>{const html=renderToStaticMarkup(createElement(Controls, { value: DEFAULT_INSTANCED_RENDERING_CONTROLS, onChange: () => {} }));expect(DEFAULT_INSTANCED_RENDERING_CONTROLS.count).toBe(50);expect(html).toContain('aria-label="Instance count (1M is an opt-in stress test)"');expect(html).toContain('value="50" selected');});
test('destroys a stale async rebuild and retains the newest completion',async()=>{vi.stubGlobal('window',{devicePixelRatio:1,addEventListener:vi.fn(),removeEventListener:vi.fn()});vi.stubGlobal('requestAnimationFrame',vi.fn(()=>1));vi.stubGlobal('cancelAnimationFrame',vi.fn());vi.stubGlobal('ResizeObserver',class{observe=vi.fn();disconnect=vi.fn();});const waits=[deferred(),deferred(),deferred()];const meshes=waits.map(()=>({destroy:vi.fn()}));let i=0;const gpu={time:0,surface:()=>({size:[100,50],format:'bgra8unorm',dispose:vi.fn()}),target:()=>({size:[100,50],format:'rgba8unorm',resize:vi.fn(),destroy:vi.fn()}),effect:()=>({set:vi.fn(),compile:vi.fn(async()=>{})}),sampler:()=>({}),mesh:()=>meshes[i],draw:()=>({set:vi.fn(),compile:()=>waits[i++].promise}),bundle:()=>({}),frame:{loop:vi.fn(()=>({stop:vi.fn()}))},dispose:vi.fn()};mocks.init.mockResolvedValueOnce(gpu);const r=createRenderer({canvas:{getBoundingClientRect:()=>({width:100,height:50})} as HTMLCanvasElement});await vi.waitFor(()=>expect(i).toBe(1));waits[0].resolve();await r.ready;r.setControls?.({count:100});await vi.waitFor(()=>expect(i).toBe(2));r.setControls?.({count:50}); // same as initial is accepted because requested state is 100
await vi.waitFor(()=>expect(i).toBe(3));waits[2].resolve();await Promise.resolve();waits[1].resolve();await vi.waitFor(()=>expect(meshes[1].destroy).toHaveBeenCalledOnce());expect(meshes[2].destroy).not.toHaveBeenCalled();r.dispose();expect(meshes[2].destroy).toHaveBeenCalledOnce();});

test('queues an early control change and installs lifecycle around the latest scene',async()=>{
 vi.stubGlobal('window',{devicePixelRatio:1,addEventListener:vi.fn(),removeEventListener:vi.fn()});vi.stubGlobal('requestAnimationFrame',vi.fn(()=>1));vi.stubGlobal('cancelAnimationFrame',vi.fn());
 const observe=vi.fn(),disconnect=vi.fn(),resizeObserver=vi.fn(function(this: {observe:typeof observe;disconnect:typeof disconnect}){this.observe=observe;this.disconnect=disconnect;});vi.stubGlobal('ResizeObserver',resizeObserver);
 const waits=[deferred(),deferred()];const meshes=waits.map(()=>({destroy:vi.fn()}));let compilation=0;
 const meshLabels:string[]=[];const mesh=vi.fn((options:{label:string})=>{meshLabels.push(options.label);return meshes[compilation];});const loop=vi.fn(()=>({stop:vi.fn()}));
 const gpu={time:0,surface:()=>({size:[100,50],format:'bgra8unorm',dispose:vi.fn()}),target:()=>({size:[100,50],format:'rgba8unorm',resize:vi.fn(),destroy:vi.fn()}),effect:()=>({set:vi.fn(),compile:vi.fn(async()=>{})}),sampler:()=>({}),mesh,draw:()=>({set:vi.fn(),compile:()=>waits[compilation++].promise}),bundle:()=>({}),frame:{loop},dispose:vi.fn()};
 mocks.init.mockResolvedValueOnce(gpu);const renderer=createRenderer({canvas:{getBoundingClientRect:()=>({width:100,height:50})} as HTMLCanvasElement});await vi.waitFor(()=>expect(compilation).toBe(1));renderer.setControls?.({count:100});waits[0].resolve();await vi.waitFor(()=>expect(compilation).toBe(2));expect(loop).not.toHaveBeenCalled();waits[1].resolve();await renderer.ready;
 expect(meshes[0].destroy).toHaveBeenCalledOnce();expect(meshLabels[1]).toBe('instanced-cubes-100');expect(loop).toHaveBeenCalledOnce();expect(resizeObserver).toHaveBeenCalledOnce();expect(observe).toHaveBeenCalledOnce();renderer.dispose();expect(meshes[1].destroy).toHaveBeenCalledOnce();
});

test('rejects the original init error, reports once, and tears down even when onError throws',async()=>{
 vi.stubGlobal('window',{devicePixelRatio:1,addEventListener:vi.fn(),removeEventListener:vi.fn()});const failure=new Error('init failed');mocks.init.mockRejectedValueOnce(failure);const onError=vi.fn(()=>{throw new Error('callback failed');});const renderer=createRenderer({canvas:{} as HTMLCanvasElement,onError});await expect(renderer.ready).rejects.toBe(failure);expect(onError).toHaveBeenCalledOnce();renderer.setControls?.({count:100});expect(onError).toHaveBeenCalledOnce();
});


test('cancellation fulfills silently without reporting an error',async()=>{vi.stubGlobal('window',{devicePixelRatio:1,addEventListener:vi.fn(),removeEventListener:vi.fn()});const onError=vi.fn();const renderer=createRenderer({canvas:{} as HTMLCanvasElement,onError});renderer.dispose();await expect(renderer.ready).resolves.toBeUndefined();expect(onError).not.toHaveBeenCalled();});

test('thumbnail compilation failure waits for submitted work and releases target and partial scene',async()=>{const failure=new Error('compile failed'),destroyMesh=vi.fn(),destroyTarget=vi.fn(),settled=vi.fn(async()=>{}),submitted=vi.fn(async()=>{});const gpu={target:()=>({size:[64,64],format:'rgba8unorm',destroy:destroyTarget}),effect:()=>({set:vi.fn(),compile:vi.fn(async()=>{})}),sampler:()=>({}),mesh:()=>({destroy:destroyMesh}),draw:()=>({set:vi.fn(),compile:vi.fn(async()=>{throw failure})}),gpu:{queue:{onSubmittedWorkDone:submitted}},settled} as never;const output={size:[64,64],format:'rgba8unorm'} as never;await expect(renderThumbnail(gpu,output)).rejects.toBe(failure);expect(submitted).toHaveBeenCalled();expect(settled).toHaveBeenCalled();expect(destroyMesh).toHaveBeenCalledOnce();expect(destroyTarget).toHaveBeenCalledOnce();});
