// This file is generated by scripts/ingest-examples.mjs. Do not edit by hand.

export interface ExampleThumbPresence {
  readonly card: string;
  readonly hero: string;
}

export const exampleThumbs: Record<string, ExampleThumbPresence> = {};
