import { mkdir,lstat,realpath,rename,rm,writeFile } from 'node:fs/promises';
import { dirname,basename,resolve,join,sep } from 'node:path';
import { ExamplesError,filesystem,integrity } from './errors.js';
import { LIMITS } from './http.js';
async function exists(path){try{return await lstat(path)}catch(e){if(e.code==='ENOENT')return undefined;throw e}}
async function safeParent(destination){const absolute=resolve(destination), parent=dirname(absolute);let cursor=parent;while(true){const s=await exists(cursor);if(s){if(s.isSymbolicLink()||!s.isDirectory())throw filesystem(`Unsafe destination parent: ${cursor}`);break}const next=dirname(cursor);if(next===cursor)break;cursor=next;}await mkdir(parent,{recursive:true,mode:0o700});const canonical=await realpath(parent);if(resolve(canonical)!==resolve(parent))throw filesystem('Destination parent contains a symlink');return {absolute,parent};}
export async function pullExample(client,manifest,destination,{force=false,offline=false}={}){
 const total=manifest.files.reduce((n,f)=>n+f.size,0);if(total>LIMITS.pull)throw integrity('Example exceeds 32 MiB pull limit');
 const {absolute,parent}=await safeParent(destination), name=basename(absolute);const lock=join(parent,`.${name}.vgpu.lock`),temp=join(parent,`.${name}.vgpu-tmp-${process.pid}-${Math.random().toString(16).slice(2)}`),backup=join(parent,`.${name}.vgpu-old-${process.pid}-${Math.random().toString(16).slice(2)}`);
 try{await mkdir(lock,{mode:0o700});}catch(e){if(e.code==='EEXIST')throw new ExamplesError('VGPU-EXAMPLES-DESTINATION-EXISTS',`Destination is busy: ${destination}`,6);throw filesystem(e.message)}
 let moved=false;
 try {const current=await exists(absolute);if(current&&!force)throw new ExamplesError('VGPU-EXAMPLES-DESTINATION-EXISTS',`Destination already exists: ${destination}`,6);if(current&&(current.isSymbolicLink()||!current.isDirectory()))throw filesystem('Destination must be a real directory');await mkdir(temp,{mode:0o700});let next=0;async function worker(){while(true){const i=next++;if(i>=manifest.files.length)return;const file=manifest.files[i],bytes=await client.getFile(manifest,file,{offline});const target=join(temp,...file.path.split('/'));if(!target.startsWith(temp+sep))throw integrity(`Path escapes destination: ${file.path}`);await mkdir(dirname(target),{recursive:true,mode:0o700});await writeFile(target,bytes,{mode:0o600,flag:'wx'});}}await Promise.all(Array.from({length:Math.min(4,manifest.files.length)},worker));if(current){await rename(absolute,backup);moved=true;}try{await rename(temp,absolute);}catch(e){if(moved)await rename(backup,absolute);moved=false;throw e}if(moved){await rm(backup,{recursive:true,force:true});moved=false;}return {out:absolute,files:manifest.files.length,bytes:total};
 }catch(e){if(e instanceof ExamplesError)throw e;throw filesystem(`Pull failed: ${e.message}`);}finally{await rm(temp,{recursive:true,force:true}).catch(()=>{});if(moved)await rename(backup,absolute).catch(()=>{});await rm(lock,{recursive:true,force:true}).catch(()=>{});}
}
