import { existsSync,renameSync,rmSync } from 'node:fs';
import { mkdir,lstat,readFile,readdir,realpath,rename,rm,writeFile } from 'node:fs/promises';
import { dirname,basename,resolve,join,sep } from 'node:path';
import { ExamplesError,filesystem,integrity } from './errors.js';
import { LIMITS } from './http.js';
async function exists(path){try{return await lstat(path)}catch(e){if(e.code==='ENOENT')return;throw e}}
async function safeParent(destination){const absolute=resolve(destination),parent=dirname(absolute);let cursor=parent;while(true){const s=await exists(cursor);if(s){if(s.isSymbolicLink()||!s.isDirectory())throw filesystem(`Unsafe destination parent: ${cursor}`);break}const next=dirname(cursor);if(next===cursor)break;cursor=next;}await mkdir(parent,{recursive:true,mode:0o700});if(resolve(await realpath(parent))!==parent)throw filesystem('Destination parent contains a symlink');return {absolute,parent};}
async function alive(pid){if(!Number.isInteger(pid)||pid<1)return false;try{process.kill(pid,0);return true}catch(e){return e.code==='EPERM'}}
function guardSignals(restore){let handled=false;const handlers={SIGINT:()=>handle('SIGINT'),SIGTERM:()=>handle('SIGTERM')},close=()=>{for(const [signal,handler] of Object.entries(handlers))process.off(signal,handler);},handle=signal=>{if(handled)return;handled=true;close();try{restore()}finally{process.kill(process.pid,signal)}};for(const [signal,handler] of Object.entries(handlers))process.once(signal,handler);return close;}
async function acquire(lock,destination){for(let attempt=0;attempt<2;attempt++){try{await mkdir(lock,{mode:0o700});await writeFile(join(lock,'owner'),`${process.pid}\n`,{mode:0o600,flag:'wx'});return}catch(e){if(e.code!=='EEXIST')throw filesystem(e.message);const s=await exists(lock);if(!s||s.isSymbolicLink()||!s.isDirectory())throw filesystem('Unsafe destination lock');let pid;try{pid=Number((await readFile(join(lock,'owner'),'utf8')).trim())}catch{}if(await alive(pid))throw new ExamplesError('VGPU-EXAMPLES-DESTINATION-EXISTS',`Destination is busy: ${destination}`,6);await rm(lock,{recursive:true});}}throw filesystem('Cannot recover stale destination lock');}
// The stable backup and PID lock form a recovery journal: after an uncatchable
// process death, the next pull restores old if unpublished or retains new if published.
async function recover(parent,name,absolute,backup){const old=await exists(backup),current=await exists(absolute);if(old){if(old.isSymbolicLink()||!old.isDirectory())throw filesystem('Unsafe stale pull backup');if(current)await rm(backup,{recursive:true});else await rename(backup,absolute);}const prefix=`.${name}.vgpu-tmp-`;for(const entry of await readdir(parent)){if(!entry.startsWith(prefix))continue;const path=join(parent,entry),s=await exists(path);if(s?.isSymbolicLink())throw filesystem('Unsafe stale pull temporary');await rm(path,{recursive:true,force:true});}}
export async function pullExample(client,manifest,destination,{force=false,offline=false,beforePublish,afterPublish}={}){
 const total=manifest.files.reduce((n,f)=>n+f.size,0);if(total>LIMITS.pull)throw integrity('Example exceeds 32 MiB pull limit');
 const {absolute,parent}=await safeParent(destination),name=basename(absolute),lock=join(parent,`.${name}.vgpu.lock`),backup=join(parent,`.${name}.vgpu-old`),temp=join(parent,`.${name}.vgpu-tmp-${process.pid}-${Math.random().toString(16).slice(2)}`);await acquire(lock,destination);
 let moved=false,published=false;
 try {await recover(parent,name,absolute,backup);const current=await exists(absolute);if(current&&!force)throw new ExamplesError('VGPU-EXAMPLES-DESTINATION-EXISTS',`Destination already exists: ${destination}`,6);if(current&&(current.isSymbolicLink()||!current.isDirectory()))throw filesystem('Destination must be a real directory');await mkdir(temp,{mode:0o700});let next=0;async function worker(){while(true){const i=next++;if(i>=manifest.files.length)return;const file=manifest.files[i],bytes=await client.getFile(manifest,file,{offline}),target=join(temp,...file.path.split('/'));if(!target.startsWith(temp+sep))throw integrity(`Path escapes destination: ${file.path}`);await mkdir(dirname(target),{recursive:true,mode:0o700});await writeFile(target,bytes,{mode:0o600,flag:'wx'});}}await Promise.all(Array.from({length:Math.min(4,manifest.files.length)},worker));const unguard=guardSignals(()=>{if(!published&&existsSync(backup)&&!existsSync(absolute)){try{renameSync(backup,absolute)}catch{}moved=false;}try{rmSync(temp,{recursive:true,force:true})}catch{}try{rmSync(lock,{recursive:true,force:true})}catch{}});try{if(current){await rename(absolute,backup);moved=true;}if(beforePublish)await beforePublish();await rename(temp,absolute);published=true;moved=false;}finally{unguard()}if(afterPublish)await afterPublish();await rm(backup,{recursive:true,force:true}).catch(()=>{});return {out:absolute,files:manifest.files.length,bytes:total};
 }catch(e){if(moved&&!published)await rename(backup,absolute).catch(()=>{});if(e instanceof ExamplesError)throw e;throw filesystem(`Pull failed: ${e.message}`);}finally{await rm(temp,{recursive:true,force:true}).catch(()=>{});await rm(lock,{recursive:true,force:true}).catch(()=>{});}
}
